Config = {}

Config.Animals = {

    -- animals
    {
        modelhash = `a_c_alligator_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_alligator',
        rewarditem2 = 'consumable_meat_alligator',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_alligator_03`,
        skinable = true,
        rewarditem1 = 'resource_skin_alligator',
        rewarditem2 = 'consumable_meat_alligator',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_badger_01`,
        skinable = true,
        rewarditem1 = 'resource_pelt_badger',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },

    {
        modelhash = `a_c_bearblack_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_bear_black',
        rewarditem2 = 'resource_tooth_bear',
        rewarditem3 = 'heart_bear',
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_bear_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_bear',
        rewarditem2 = 'resource_tooth_bear',
        rewarditem3 = 'heart_bear',
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_beaver_01`,
        skinable = true,
        rewarditem1 = 'resource_pelt_beaver',
        rewarditem2 = 'resource_tail_beaver',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_bighornram_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_ram',
        rewarditem2 = 'resource_horn_ram',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_boar_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_boar',
        rewarditem2 = 'heart_pig_boar',
        rewarditem3 = 'resource_tusk_boar',
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_buck_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_buck',
        rewarditem2 = 'resource_antler_buck',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_buffalo_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_buffalo',
        rewarditem2 = 'resource_horn_buffalo',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_bull_01`,
        skinable = true,
        rewarditem1 = 'resource_hide_cow_bull',
        rewarditem2 = 'resource_horn_bull',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_cougar_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_cougar',
        rewarditem2 = 'heart_cougar',
        rewarditem3 = 'resource_tooth_cougar',
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_cow`,
        skinable = true,
        rewarditem1 = 'resource_hide_cow1',
        rewarditem2 = 'resource_horn_cow',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_coyote_01`,
        skinable = true,
        rewarditem1 = 'resource_pelt_coyote',
        rewarditem2 = 'resource_tooth_coyote',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_deer_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_deer',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_elk_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_elk',
        rewarditem2 = 'resource_antler_elk',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_fox_01`,
        skinable = true,
        rewarditem1 = 'resource_pelt_fox',
        rewarditem2 = 'resource_tooth_fox',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_goat_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_goat',
        rewarditem2 = 'resource_head_goat',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_javelina_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_javelina_boar',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_moose_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_moose',
        rewarditem2 = 'resource_antler_moose',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_ox_01`,
        skinable = true,
        rewarditem1 = 'resource_hide_cow_ox',
        rewarditem2 = 'resource_horn_ox',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_panther_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_panther',
        rewarditem2 = 'resource_claw_panther',
        rewarditem3 = 'heart_panther',
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_pig_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_pig',
        rewarditem2 = 'pigs_feet',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_pronghorn_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_pronghorn',
        rewarditem2 = 'resource_horn_pronghorn',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_sheep_01`,
        skinable = true,
        rewarditem1 = 'resource_wool',
        rewarditem2 = 'resource_head_sheep',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_wolf`,
        skinable = true,
        rewarditem1 = 'resource_pelt_wolf',
        rewarditem2 = 'resource_tooth_wolf',
        rewarditem3 = 'heart_wolf',
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_wolf_medium`,
        skinable = true,
        rewarditem1 = 'resource_pelt_wolf',
        rewarditem2 = 'resource_tooth_wolf',
        rewarditem3 = 'heart_wolf',
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_wolf_small`,
        skinable = true,
        rewarditem1 = 'resource_pelt_wolf',
        rewarditem2 = 'resource_tooth_wolf',
        rewarditem3 = 'heart_wolf',
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    -- small animals
    {
        modelhash = `a_c_bat_01`,
        skinable = false,
        rewarditem1 = 'a_c_bat_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_bluejay_01`,
        skinable = false,
        rewarditem1 = 'a_c_bluejay_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_californiacondor_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_condor',
        rewarditem2 = 'provision_beak_condor',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_cardinal_01`,
        skinable = false,
        rewarditem1 = 'a_c_cardinal_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_carolinaparakeet_01`,
        skinable = false,
        rewarditem1 = 'a_c_carolinaparakeet_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_cedarwaxwing_01`,
        skinable = false,
        rewarditem1 = 'a_c_cedarwaxwing_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_chicken_01`,
        skinable = true,
        rewarditem1 = 'heart_chicken',
        rewarditem2 = 'provision_feather_chicken',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_chipmunk_01`,
        skinable = false,
        rewarditem1 = 'a_c_chipmunk_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_cormorant_01`,
        skinable = true,
        rewarditem1 = 'provision_beak_cormorant',
        rewarditem2 = 'provision_feather_cormorant',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_crab_01`,
        skinable = false,
        rewarditem1 = 'a_c_crab_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_cranewhooping_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_crane',
        rewarditem2 = 'provision_beak_crane',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_crow_01`,
        skinable = false,
        rewarditem1 = 'a_c_crow_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_duck_01`,
        skinable = true,
        rewarditem1 = 'heart_duck',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_eagle_01`,
        skinable = true,
        rewarditem1 = 'resource_claw_eagle',
        rewarditem2 = 'provision_feather_eagle',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_egret_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_egret',
        rewarditem2 = 'provision_beak_egret',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_frogbull_01`,
        skinable = false,
        rewarditem1 = 'a_c_frogbull_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_gilamonster_01`,
        skinable = false,
        rewarditem1 = 'resource_skin_gilamonster',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_goosecanada_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_goose',
        rewarditem2 = 'provision_beak_goose',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_hawk_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_hawk',
        rewarditem2 = 'resource_claw_hawk',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_heron_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_heron',
        rewarditem2 = 'provision_beak_heron',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_iguanadesert_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_desert_iguana',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_iguana_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_iguana',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_loon_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_loon',
        rewarditem2 = 'provision_beak_common_loon',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_muskrat_01`,
        skinable = true,
        rewarditem1 = 'resource_pelt_muskrat',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_oriole_01`,
        skinable = false,
        rewarditem1 = 'a_c_oriole_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_owl_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_owl',
        rewarditem2 = 'resource_claw_owl',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_parrot_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_parrot',
        rewarditem2 = 'provision_beak_parrot',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_pelican_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_pelican',
        rewarditem2 = 'provision_beak_pelican',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_pheasant_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_pheasant',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_pigeon`,
        skinable = false,
        rewarditem1 = 'a_c_pigeon',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_possum_01`,
        skinable = true,
        rewarditem1 = 'a_c_possum_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_prairiechicken_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_prairie_chicken',
        rewarditem2 = 'provision_beak_prairie_chicken',
        rewarditem3 = 'heart_chicken',
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_quail_01`,
        skinable = false,
        rewarditem1 = 'a_c_quail_01', -- image needed
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_rabbit_01`,
        skinable = true,
        rewarditem1 = 'resource_pelt_rabbit',
        rewarditem2 = 'resource_foot_rabbit',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_raccoon_01`,
        skinable = true,
        rewarditem1 = 'resource_pelt_raccoon',
        rewarditem2 = 'resource_tooth_raccoon',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_rat_01`,
        skinable = false,
        rewarditem1 = 'a_c_rat_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_raven_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_raven',
        rewarditem2 = 'resource_claw_raven',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_redfootedbooby_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_red_footed_booby',
        rewarditem2 = 'provision_beak_red_footed_booby',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_robin_01`,
        skinable = false,
        rewarditem1 = 'a_c_robin_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_rooster_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_rooster',
        rewarditem2 = 'resource_claw_rooster',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_roseatespoonbill_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_roseta_spoonbill',
        rewarditem2 = 'provision_beak_roseate_spoonbill',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_seagull_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_seagull',
        rewarditem2 = 'provision_beak_seagull',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_skunk_01`,
        skinable = true,
        rewarditem1 = 'resource_pelt_skunk',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_snakeblacktailrattle_01`,
        skinable = true,
        rewarditem1 = 'resource_snake_generic_skin',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_snakeferdelance_01`,
        skinable = true,
        rewarditem1 = 'resource_snake_generic_skin',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_snakeredboa10ft_01`,
        skinable = true,
        rewarditem1 = 'resource_snake_generic_skin',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_snakeredboa_01`,
        skinable = true,
        rewarditem1 = 'resource_snake_generic_skin',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_snakewater_01`,
        skinable = true,
        rewarditem1 = 'resource_snake_generic_skin',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_snake_01`,
        skinable = true,
        rewarditem1 = 'resource_snake_generic_skin',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_songbird_01`,
        skinable = false,
        rewarditem1 = 'a_c_songbird_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_sparrow_01`,
        skinable = false,
        rewarditem1 = 'a_c_sparrow_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_squirrel_01`,
        skinable = false,
        rewarditem1 = 'a_c_squirrel_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_toad_01`,
        skinable = false,
        rewarditem1 = 'a_c_toad_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_turkeywild_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_turkey',
        rewarditem2 = 'provision_beak_turkey',
        rewarditem3 = 'heart_turkey',
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_turkey_01`,
        skinable = true,
        rewarditem1 = 'provision_feather_turkey',
        rewarditem2 = 'provision_beak_turkey',
        rewarditem3 = 'heart_turkey',
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_turkey_02`,
        skinable = true,
        rewarditem1 = 'provision_feather_turkey',
        rewarditem2 = 'provision_beak_turkey',
        rewarditem3 = 'heart_turkey',
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_turtlesea_01`,
        skinable = true,
        rewarditem1 = 'resource_shell_turtle',
        rewarditem2 = 'provision_beak_turtle',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_turtlesnapping_01`,
        skinable = true,
        rewarditem1 = 'resource_shell_turtle',
        rewarditem2 = 'provision_beak_turtle',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_vulture_01`,
        skinable = true,
        rewarditem1 = nil,
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_woodpecker_01`,
        skinable = false,
        rewarditem1 = 'a_c_woodpecker_01',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_woodpecker_02`,
        skinable = false,
        rewarditem1 = 'a_c_woodpecker_02',
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    -- legendary
    {
        modelhash = `a_c_alligator_02`,
        skinable = true,
        rewarditem1 = 'resource_skin_alligator_legendary',
        rewarditem2 = 'consumable_meat_alligator',
        rewarditem3 = 'resource_tooth_alligator',
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_boarlegendary_01`,
        skinable = false,
        rewarditem1 = 'resource_skin_boar_legendary',
        rewarditem2 = 'heart_pig_boar',
        rewarditem3 = 'resource_tusk_boar',
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = `a_c_buffalo_tatanka_01`,
        skinable = true,
        rewarditem1 = 'resource_skin_buffalo_legendary',
        rewarditem2 = 'resource_horn_buffalo',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },

}
