Config = {}

Config.Animals = {

    {
        modelhash = -1797625440,
        name = "Armadillo",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1170118274,
        name = "American Badger",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 1755643085,
        name = "American Pronghorn Doe",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1124266369,
        name = "Bear",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1568716381,
        name = "Big Horn Ram",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1963605336,
        name = "Buck",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 1556473961,
        name = "Bison",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = 'leather',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 367637652,
        name = "Bison",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = 'leather',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 1957001316,
        name = "Bull",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = 'leather',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 1110710183,
        name = "Deer",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1003616053,
        name = "Duck",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 1459778951,
        name = "Eagle",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 831859211,
        name = "Egret",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 252669332,
        name = "American Red Fox",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1143398950,
        name = "Big Grey Wolf",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -885451903,
        name = "Medium Grey Wolf",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -829273561,
        name = "Small Grey Wolf",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 1104697660,
        name = "Vulture",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -407730502,
        name = "Snapping Turtle",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -466054788,
        name = "Wild Turkey",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -2011226991,
        name = "Wild Turkey",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -166054593,
        name = "Wild Turkey",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -22968827,
        name = "Water Snake",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -229688157,
        name = "CottonMouth Water Snake",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1790499186,
        name = "Snake Red Boa",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 1464167925,
        name = "Snake Fer-De-Lance",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 846659001,
        name = "Black-Tailed Rattlesnake",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 545068538,
        name = "Western Rattlesnake",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -121266332,
        name = "Striped Skunk",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 40345436,
        name = "Merino Sheep",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -164963696,
        name = "Herring Seagull",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1076508705,
        name = "Roseate Spoonbill",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 2023522846,
        name = "Dominique Rooster",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -466687768,
        name = "Red-Footed Booby",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    [-575340245]  = {
        modelhash = -575340245,
        name = "Wester Raven",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 1458540991,
        name = "North American Racoon",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -541762431,
        name = "Black-Tailed Jackrabbit",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 2079703102,
        name = "Greater Prairie Chicken",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1414989025,
        name = "Wirginia Possum",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 1007418994,
        name = "Berkshire Pig",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 1416324601,
        name = "Ring-Necked Pheasant",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 1265966684,
        name = "American White Pelican",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1797450568,
        name = "Blue And Yellow Macaw",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 1654513481,
        name = "Panther",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 120598262,
        name = "Californian Condor",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -2063183075,
        name = "Dominique Chicken",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -2073130256,
        name = "Double-Crested Cormorant",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 90264823,
        name = "Cougar",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -50684386,
        name = "Florida Cracker Cow",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = 'leather',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 480688259,
        name = "Coyote",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -564099192,
        name = "Whooping Crane",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 45741642,
        name = "Gila Monster",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -753902995,
        name = "Alpine Goat",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 723190474,
        name = "Canada Goose",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -2145890973,
        name = "Ferruinous Hawk",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 1095117488,
        name = "Great Blue Heron",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1854059305,
        name = "Green Iguana",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -593056309,
        name = "Desert Iguana",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 1751700893,
        name = "Peccary Pig",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 386506078,
        name = "Common Loon",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1098441944,
        name = "Moose",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = 'leather',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1134449699,
        name = "American Muskrat",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -86244272,
        name = "Great Horned Owl",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 556355544,
        name = "Angus Ox",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = 'leather',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1892280447,
        name = "Alligator Small",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -2004866590,
        name = "Alligator",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1295720802,
        name = "Northen American Alligator",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 759906147,
        name = "North American Beaver",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 730092646,
        name = "American Black Bear",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 195700131,
        name = "Hereford Bull",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = 'leather',
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
	------------------------------
	-- legendary
	------------------------------
    {
        modelhash = -2021043433,
        name = "Legendary White Elk",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1747620994,
        name = "Legendary Boa",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 674287411,
        name = "Legendary Sun Alligator",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1598866821,
        name = "Legendary Bull Alligator",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1149999295,
        name = "Legendary White Beaver",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = 2028722809,
        name = "Legendary Gaint Boar",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -389300196,
        name = "Legendary WakpaBoar",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1433814131,
        name = "Legendary Maza Cougar",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1307757043,
        name = "Legendary Midnight Paw Coyote",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1189368951,
        name = "Legendary Ghost Panther",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1392359921,
        name = "Legendary Onyx Wolf",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -551216071,
        name = "Legendary Owiza Bear",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -511163808,
        name = "Legendary Chalk Horn Ram",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -1754211037,
        name = "Legendary Buck",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -915290938,
        name = "Legendary Winyan Bison",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
    {
        modelhash = -117665949,
        name = "Legendary Snowflake Moose",
        rewarditem1 = 'raw_meat', 
        rewarditem2 = nil,
        rewarditem3 = nil,
        rewarditem4 = nil,
        rewarditem5 = nil,
    },
}
